# credit: https://docs.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions

name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      OUT_PATH: test/data/out
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Static checks
        run: cd scripts && python -m flake8 && cd .. # flake8 settings in [ROOT]/tox.ini
      - name: Test with pytest & calculate coverage
        run: |
          cd test
          python -m pytest --cov=../scripts/ . && mv .coverage ..
          cd ..
          coverage xml -o $OUT_PATH/coverage/coverage.xml
        if: success() || failure() # run even if the previous step fails
      - name: Generate HTML code coverage report
        run: coverage html -d $OUT_PATH/coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ${{ env.OUT_PATH }}/coverage/coverage.xml
      - name: Publish tests artifacts
        uses: actions/upload-artifact@v1
        with:
          name: tests output
          path: ${{ env.OUT_PATH }}
        if: success() || failure()
